name: coffee_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.5.1

dependencies:
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  logger: ^2.4.0


flutter:
  fonts:
    - family: seaweed
      fonts:
        - asset: assets/fonts/seaweed_script_regular.ttf

  uses-material-design: true

  assets:
    - assets/images/menu/
    - assets/saves/
    - assets/images/icons/coffee_cup.svg
    - assets/images/icons/arrow.svg
    - assets/images/icons/home.svg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icons/coffee_cup_b.jpg
  android_12: 
    image: assets/images/icons/coffee_cup_b.jpg

